### ISSUE TITLE
Invalid value "undefined" for header "Content-Type"

### ISSUE THREAD

**Issue by rubensworks** [comunica/rdf-test-suite-ldf.js#26]
When executing SPARQL test simple03 with Comunica, I get the following error:

```
(node:83950) UnhandledPromiseRejectionWarning: TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Content-Type"
    at storeHeader (_http_outgoing.js:411:5)
    at processHeader (_http_outgoing.js:406:3)
    at ServerResponse._storeHeader (_http_outgoing.js:312:9)
    at ServerResponse.writeHead (_http_server.js:271:8)
    at mockFetcher.parseMockedResponse.then (/Users/rtaelman/Documents/UGent/nosync/rdf-test-suite-ldf.js/lib/testcase/ldf/mock/LdfResponseMocker.js:54:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:83950) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:83950) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I've done some debugging, and it looks like the content type header is not available in the mocked file.
@ManuDeBuck Is this a problem in the recorder? Or should the test suite runner be able to handle these empty content types?

**Comment by ManuDeBuck** [comment]
@rubensworks this is an issue in the code of the `rdf-test-suite-ldf.js` and I will fix it RN.

**Comment by ManuDeBuck** [comment]
Note to self: this seems a fun testcase for `jest`-testing
